# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

let
  url = "https://design.home.local";
  secretsFile = /var/lib/secrets/penpot;
in
{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."penpot-penpot-backend" = {
    image = "penpotapp/backend:latest";
    environment = {
      "PENPOT_DATABASE_PASSWORD" = "penpot";
      "PENPOT_DATABASE_URI" = "postgresql://penpot-postgres/penpot";
      "PENPOT_DATABASE_USERNAME" = "penpot";
      "PENPOT_FLAGS" =
        "disable-registration disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies";
      "PENPOT_HTTP_SERVER_MAX_BODY_SIZE" = "31457280";
      "PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE" = "367001600";
      "PENPOT_OBJECTS_STORAGE_BACKEND" = "fs";
      "PENPOT_OBJECTS_STORAGE_FS_DIRECTORY" = "/opt/data/assets";
      "PENPOT_PUBLIC_URI" = url;
      "PENPOT_REDIS_URI" = "redis://penpot-valkey/0";
      "PENPOT_SMTP_DEFAULT_FROM" = "no-reply@example.com";
      "PENPOT_SMTP_DEFAULT_REPLY_TO" = "no-reply@example.com";
      "PENPOT_SMTP_HOST" = "penpot-mailcatch";
      "PENPOT_SMTP_PORT" = "1025";
      "PENPOT_SMTP_SSL" = "false";
      "PENPOT_SMTP_TLS" = "false";
      "PENPOT_TELEMETRY_ENABLED" = "false";
      "PENPOT_TELEMETRY_REFERER" = "compose";
    };
    environmentFiles = [ secretsFile ];
    volumes = [
      "penpot_penpot_assets:/opt/data/assets:rw"
    ];
    dependsOn = [
      "penpot-penpot-postgres"
      "penpot-penpot-valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-backend"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_assets.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_assets.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-exporter" = {
    image = "penpotapp/exporter:latest";
    environment = {
      "PENPOT_PUBLIC_URI" = url;
      "PENPOT_REDIS_URI" = "redis://penpot-valkey/0";
    };
    environmentFiles = [ secretsFile ];
    dependsOn = [
      "penpot-penpot-valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-exporter"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-exporter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-frontend" = {
    image = "penpotapp/frontend:latest";
    environment = {
      "PENPOT_FLAGS" =
        "disable-registration disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies";
      "PENPOT_HTTP_SERVER_MAX_BODY_SIZE" = "31457280";
      "PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE" = "367001600";
    };
    volumes = [
      "penpot_penpot_assets:/opt/data/assets:rw"
    ];
    ports = [
      "9001:8080/tcp"
    ];
    dependsOn = [
      "penpot-penpot-backend"
      "penpot-penpot-exporter"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-frontend"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_assets.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_assets.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-mailcatch" = {
    image = "sj26/mailcatcher:latest";
    ports = [
      "1080:1080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=penpot-mailcatch"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-mailcatch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-postgres" = {
    image = "postgres:15";
    environment = {
      "POSTGRES_DB" = "penpot";
      "POSTGRES_INITDB_ARGS" = "--data-checksums";
      "POSTGRES_PASSWORD" = "penpot";
      "POSTGRES_USER" = "penpot";
    };
    volumes = [
      "penpot_penpot_postgres_v15:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U penpot"
      "--health-interval=2s"
      "--health-retries=5"
      "--health-start-period=2s"
      "--health-timeout=10s"
      "--network-alias=penpot-postgres"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_postgres_v15.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
      "podman-volume-penpot_penpot_postgres_v15.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };
  virtualisation.oci-containers.containers."penpot-penpot-valkey" = {
    image = "valkey/valkey:8.1";
    environment = {
      "VALKEY_EXTRA_FLAGS" = "--maxmemory 128mb --maxmemory-policy volatile-lfu";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=valkey-cli ping | grep PONG"
      "--health-interval=1s"
      "--health-retries=5"
      "--health-start-period=3s"
      "--health-timeout=3s"
      "--network-alias=penpot-valkey"
      "--network=penpot_penpot"
    ];
  };
  systemd.services."podman-penpot-penpot-valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-penpot_penpot.service"
    ];
    requires = [
      "podman-network-penpot_penpot.service"
    ];
    partOf = [
      "podman-compose-penpot-root.target"
    ];
    wantedBy = [
      "podman-compose-penpot-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-penpot_penpot" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f penpot_penpot";
    };
    script = ''
      podman network inspect penpot_penpot || podman network create penpot_penpot
    '';
    partOf = [ "podman-compose-penpot-root.target" ];
    wantedBy = [ "podman-compose-penpot-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-penpot_penpot_assets" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect penpot_penpot_assets || podman volume create penpot_penpot_assets
    '';
    partOf = [ "podman-compose-penpot-root.target" ];
    wantedBy = [ "podman-compose-penpot-root.target" ];
  };
  systemd.services."podman-volume-penpot_penpot_postgres_v15" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect penpot_penpot_postgres_v15 || podman volume create penpot_penpot_postgres_v15
    '';
    partOf = [ "podman-compose-penpot-root.target" ];
    wantedBy = [ "podman-compose-penpot-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-penpot-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
