# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."invokeai-invokeai-cuda" = {
    image = "ghcr.io/invoke-ai/invokeai:latest";
    environment = {
      "INVOKEAI_ROOT" = "/invokeai";
    };
    volumes = [
      "/home/camdenboren/.cache/huggingface:/invokeai/.cache/huggingface:rw"
      "/home/camdenboren/invokeai:/invokeai:rw"
    ];
    ports = [
      "9090:9090/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=invokeai-cuda"
      "--network=invokeai_default"
    ];
  };
  systemd.services."podman-invokeai-invokeai-cuda" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-invokeai_default.service"
    ];
    requires = [
      "podman-network-invokeai_default.service"
    ];
    partOf = [
      "podman-compose-invokeai-root.target"
    ];
    wantedBy = [
      "podman-compose-invokeai-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-invokeai_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f invokeai_default";
    };
    script = ''
      podman network inspect invokeai_default || podman network create invokeai_default
    '';
    partOf = [ "podman-compose-invokeai-root.target" ];
    wantedBy = [ "podman-compose-invokeai-root.target" ];
  };

  # Builds
  systemd.services."podman-build-invokeai-invokeai-cuda" = {
    path = [
      pkgs.podman
      pkgs.git
    ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/camdenboren/InvokeAI
      podman build -t ghcr.io/invoke-ai/invokeai:latest -f docker/Dockerfile .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-invokeai-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
