name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host-name: main
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: mainvm
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: media
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: mac
            cfg-key: darwin
            os-label: macos-latest

          - host-name: macvm
            cfg-key: nixos
            os-label: ubuntu-24.04-arm

    name: ${{ matrix.host-name }}
    runs-on: ${{ matrix.os-label }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ matrix.host-name }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ matrix.host-name }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ matrix.host-name }}-
          purge-created: 0
          purge-last-accessed: P1DT12H
          purge-primary-key: never

      - run: nix build .#${{ matrix.cfg-key }}Configurations.${{ matrix.host-name }}.config.system.build.toplevel
