name: scan

on:
  push:
    branches-ignore: ["update*"]
    paths:
      - "flake.lock"
  pull_request:
    paths:
      - "flake.lock"
  schedule:
    # should be UTC-5 + UTC-6, but UTC-7:15 + UTC-8:15 works better
    - cron: "45 10 * 4-10 *" # Every day at 8am CDT
    - cron: "45 11 * 1-3,11-12 *" # Every day at 8am CST

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host-name: main
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: mainvm
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: media
            cfg-key: nixos
            os-label: ubuntu-latest

          - host-name: mac
            cfg-key: darwin
            os-label: macos-latest

          - host-name: macvm
            cfg-key: nixos
            os-label: ubuntu-24.04-arm

    name: ${{ matrix.host-name }}
    runs-on: ${{ matrix.os-label }}
    steps:
      - if: ${{ matrix.host-name == 'main' }}
        uses: insightsengineering/disk-space-reclaimer@v1

      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ matrix.host-name }}-${{ hashFiles('**/flake.lock') }}
          save: false

      - name: Install deps via nixpkgs and run vulnxscan + script
        run: |
          nix shell nixpkgs#sbomnix nixpkgs#python3 --command sh -c \
            "vulnxscan .#${{ matrix.cfg-key }}Configurations.${{ matrix.host-name }}.config.system.build.toplevel && \
            python common/usr/scr/vulnxscan.py >> summary.md"

      - name: Cat scan results to the job summary
        run: cat summary.md | tee $GITHUB_STEP_SUMMARY
